logging:
  receivers:
    my-system-receiver:
      type: files
      include_paths:
        - "/var/log/webapp/*.log"
      record_log_file_path: true
  processors:
    my-app-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%d %H:%M:%S"
    logback-level-processor:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.level
  service:
    pipelines:
      default_pipeline:
        receivers: [my-system-receiver]
        processors: [my-app-processor, logback-level-processor]